#!/bin/sh

DATA=/mnt/data
PERS=/mnt/persist
SERVICE=/usr/sbin/service

if [ $(id -u) != "0" ]
then
    echo "You must run this script as root."
    exit 1
fi

echo
echo "**********************************************************"
echo "* WARNING:                                               *"
echo "* This program will erase ALL DATA ON THIS DEVICE.       *"
echo "**********************************************************"
echo
read -n 1 -p "Proceed with factory reset? [y/N] " yesno
echo

if [ "$yesno" != y ] && [ "$yesno" != Y ]
then
    exit
fi

$SERVICE librarian stop
$SERVICE monitoring stop
$SERVICE fsal stop
$SERVICE ondd stop

echo -n "Removing data: "
rm -rf $DATA/*
rm -rf $PERS/*
echo "DONE"

echo "Rebooting..."
reboot
