#!/bin/sh

# As much as we'd like to do a proper shutdown, most likely the power was 
# pulled

# export a path to save us headaches when there is no path
PATH=/bin:/sbin:/usr/bin:/usr/sbin

# Save time to HW clock
[ -f /dev/rtc ] && /sbin/hwclock -u -w

# This never hurts
/bin/sync

for f in $(ls -r /etc/init.d/S*)
do
    [ ! -f "$f" ] && continue # Ignore dangling symlinks (if any).
    [ -x "$f" ] && $f stop
done

# Wait for all processes to finish
wait
