#!/bin/sh

# export a path to save us headaches when there is no path
PATH=/bin:/sbin:/usr/bin:/usr/sbin

# Start status LED blinking
/bin/echo 3 > /sys/class/leds/status/brightness
/bin/echo timer > /sys/class/leds/status/trigger
/bin/echo 250 > /sys/class/leds/status/delay_on
/bin/echo 250 > /sys/class/leds/status/delay_off

# Enable HDMI output
. /sbin/hdmi_config

# Ensure the time is reasonably recent so that the certificate works until we 
# get the correct time from ONDD or NTP.
if [ $(/bin/date +%s) -lt 1420070400 ]; then
    date -s 201501010000.00
fi

export LANG='en_US.UTF-8'

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for f in /etc/init.d/S??* ;do
    [ ! -f "$f" ] && continue # Ignore dangling symlinks (if any).
    [ -x "$f" ] && $f start
done
